### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by wehrdesigns** [stnkl/FastLEDHub#1]
This is a great project!  Thanks for sharing!  I will note that I had to add the blank file "config_json.txt" to the data folder before a webpage would load.  The code did not automatically create one if it was supposed to.  Keep up the great work!  I would like to add a sunrise feature if you don't already have it written.

**Comment by srwi** [comment]
Thank you!

There is an alarm function which allows you to slowly fade in an animation or a static color over a set period of time. Could you use that as a sunrise feature? Otherwise feel free to send a PR!

I will look into the config file bug. Thank you for the report!

**Comment by wehrdesigns** [comment]
I tried the alarm feature, it works good as a sunrise!  Thanks again!

**Comment by srwi** [comment]
I am having trouble reproducing the config file issue. Do you remember the output? Did the ESP reset when loading a page? The file gets created successfully for me.
