### ISSUE TITLE
analogRead A0 pin assignment

### ISSUE THREAD

**Issue by gootzte** [stnkl/FastLEDHub#13]
After working with different ESP32 boards, the A0 in the analogRead(A0) function needs to be replaced with m_potentiometerPin member.  Most ESP32 boards has 4 or more GPIO pins that can be assigned for analog input.   The default A0 may not always be the assigned correctly and will cause issues.    On the board I am using A0 is defaulted to pin 36 but according to espressif pins 36 & 39 are used for the internal hall sensor.

**Comment by srwi** [comment]
Thanks again for your bug reports and the detailed explanation. As you can probably tell, I didn't spend enough time testing the hardware inputs. I will take care of the issue.
