### ISSUE TITLE
error: 'gpio_matrix_out' was not declared in this scope

### ISSUE THREAD

**Issue by huster-songtao** [stnkl/FastLEDHub#17]
```
#define FASTLED_INTERNAL                             //  Otherwise FastLED shows compile messages
#include <FastLEDHub.h>

#define NUM_LEDS 100
#define LED_TYPE WS2812B
#define LIGHTSTRIP_PIN 5

CRGB leds[NUM_LEDS];

void setup()
{
  FastLEDHub.initialize("Project Name");
  FastLEDHub.addLeds<LED_TYPE, LIGHTSTRIP_PIN, GRB>(leds, NUM_LEDS);
}

void loop()
{
  FastLEDHub.handle();
}
```

d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:266:29: error: 'RMTMEM' was not declared in this scope
  266 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:347:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  347 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out

exit status 1

Compilation error: exit status 1

![20231109160247](https://github.com/srwi/FastLEDHub/assets/94954133/4d72d9af-ab59-4087-a02d-a1741ad86c8b)

**Comment by srwi** [comment]
Are you using version 3.0.0alpha2 of the Arduino for esp32? It looks like FastLED is affected by a bug: https://github.com/FastLED/FastLED/issues/1553

I would advise you to downgrade to an earlier version. I am using version 2.0.13 successfully:

![grafik](https://github.com/srwi/FastLEDHub/assets/17520641/260f46d9-1e33-44fc-96c8-a24c1e4a6ae2)

**Comment by huster-songtao** [comment]
> Are you using version 3.0.0alpha2 of the Arduino for esp32? It looks like FastLED is affected by a bug: [FastLED/FastLED#1553](https://github.com/FastLED/FastLED/issues/1553)
> 
> I would advise you to downgrade to an earlier version. I am using version 2.0.13 successfully:
> 
> ![grafik](https://user-images.githubusercontent.com/17520641/282137454-260f46d9-1e33-44fc-96c8-a24c1e4a6ae2.png)

Yes, I am using 3.0.0-alpha2 of the Arduino for esp32 by Espressif Systems.

![20231113154600](https://github.com/srwi/FastLEDHub/assets/94954133/771ab2d1-3ca7-4755-b849-c43b61920d27)

I am using version 2.0.13 successfully.
Thanks you very much.
Welcome to ChongQing, China, I'll treat you to Chongqing hot pot.

**Comment by SylvianHemus** [comment]
I am not using 3.0.0-alpha, using ESP-IDF and have the same problem on the most recent
