### ISSUE TITLE
ESP8266 Crashes with 256 LEDs

### ISSUE THREAD

**Issue by jamesmendel** [stnkl/FastLEDHub#2]
In:
https://github.com/stnkl/FastLEDManager/blob/1f2515761246a01832a0cc2bddc1dc267d8a76ce/Hardware.cpp#L59

Use  `uint16_t` to fix this issue.

(sorry, I'm a noob wit Git; I think I'm supposed to do a pull request... but not certain :D)

**Comment by srwi** [comment]
Awesome find! Sorry for the late reply. Your fix will be available once FastLEDManager has been converted into a library (#3). It will then be available via the Arduino library manager.
