### ISSUE TITLE
Using board 'dfrobot_beetle_esp32c6, #error Not yet implemented for unknown ESP32 target

### ISSUE THREAD

**Issue by huster-songtao** [stnkl/FastLEDHub#26]
FQBN: esp32:esp32:dfrobot_beetle_esp32c6:CDCOnBoot=cdc
Using board 'dfrobot_beetle_esp32c6' from platform in folder: C:\Users\tao\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-rc1
Using core 'esp32' from platform in folder: C:\Users\tao\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-rc1

"C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp-rv32\\2302/bin/riscv32-esp-elf-g++" -MMD -c "@C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/flags/cpp_flags" -w -Os -DF_CPU=160000000L -DARDUINO=10607 -DARDUINO_DFROBOT_BEETLE_ESP32C6 -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"DFROBOT_BEETLE_ESP32C6\"" "-DARDUINO_VARIANT=\"dfrobot_beetle_esp32c6\"" -DARDUINO_PARTITION_default "-DARDUINO_HOST_OS=\"windows\"" "-DARDUINO_FQBN=\"esp32:esp32:dfrobot_beetle_esp32c6:UploadSpeed=921600,CDCOnBoot=cdc,CPUFreq=160,FlashFreq=80,FlashMode=qio,FlashSize=4M,PartitionScheme=default,DebugLevel=none,EraseFlash=none,JTAGAdapter=default\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 "@C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/flags/defines" "-IC:\\Users\\tao\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2024327-1028-t9wqqk.94axi\\BasicExample" -iprefix "C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/include/" "@C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/flags/includes" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/qio_qspi/include" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\cores\\esp32" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\variants\\dfrobot_beetle_esp32c6" "-Id:\\Arduino\\Sketchbook\\libraries\\FastLEDHub\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\FastLED\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\ArduinoJson\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\LinkedList" "-Id:\\Arduino\\Sketchbook\\libraries\\ESPEssentials\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\ArduinoOTA\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\Network\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\Update\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\FS\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\HTTPUpdateServer\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\SPIFFS\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\WebServer\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\WiFiManager" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\WiFi\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\DNSServer\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\AsyncUDP\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\Ticker\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\LittleFS\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\HTTPClient\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\NetworkClientSecure\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\WebSockets\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\ESPmDNS\\src" "@C:\\Users\\tao\\AppData\\Local\\Temp\\arduino\\sketches\\02B62C00B6984C7134C611F230200084/build_opt.h" "@C:\\Users\\tao\\AppData\\Local\\Temp\\arduino\\sketches\\02B62C00B6984C7134C611F230200084/file_opts" "d:\\Arduino\\Sketchbook\\libraries\\FastLED\\src\\platforms.cpp" -o "C:\\Users\\tao\\AppData\\Local\\Temp\\arduino\\sketches\\02B62C00B6984C7134C611F230200084\\libraries\\FastLED\\platforms.cpp.o"
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:330:6: error: #error Not yet implemented for unknown ESP32 target
  330 |     #error Not yet implemented for unknown ESP32 target
      |      ^~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:394:6: error: #error Not yet implemented for unknown ESP32 target
  394 |     #error Not yet implemented for unknown ESP32 target
      |      ^~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:440:10: error: #error Not yet implemented for unknown ESP32 target
  440 |         #error Not yet implemented for unknown ESP32 target
      |          ^~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:266:29: error: 'RMTMEM' was not declared in this scope
  266 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:347:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  347 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out
In file included from C:\Users\tao\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-3662303f312/esp32c6/include/esp_system/include/esp_system.h:14,
                 from C:\Users\tao\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-rc1\cores\esp32/esp32-hal.h:32,
                 from d:\Arduino\Sketchbook\libraries\FastLED\src/platforms/esp/32/led_sysdefs_esp32.h:2,
                 from d:\Arduino\Sketchbook\libraries\FastLED\src/led_sysdefs.h:42,
                 from d:\Arduino\Sketchbook\libraries\FastLED\src/FastLED.h:51,
                 from d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:7:
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::interruptHandler(void*)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:445:31: error: 'tx_next_bit' was not declared in this scope
  445 |             if (intr_st & BIT(tx_next_bit)) {
      |                               ^~~~~~~~~~~
C:\Users\tao\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-3662303f312/esp32c6/include/esp_common/include/esp_bit_defs.h:79:42: note: in definition of macro 'BIT'
   79 | #define BIT(nr)                 (1UL << (nr))
      |                                          ^~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:451:35: error: 'tx_done_bit' was not declared in this scope
  451 |                 if (intr_st & BIT(tx_done_bit)) {
      |                                   ^~~~~~~~~~~
C:\Users\tao\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-3662303f312/esp32c6/include/esp_common/include/esp_bit_defs.h:79:42: note: in definition of macro 'BIT'
   79 | #define BIT(nr)                 (1UL << (nr))
      |                                          ^~
"C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp-rv32\\2302/bin/riscv32-esp-elf-g++" -MMD -c "@C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/flags/cpp_flags" -w -Os -DF_CPU=160000000L -DARDUINO=10607 -DARDUINO_DFROBOT_BEETLE_ESP32C6 -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"DFROBOT_BEETLE_ESP32C6\"" "-DARDUINO_VARIANT=\"dfrobot_beetle_esp32c6\"" -DARDUINO_PARTITION_default "-DARDUINO_HOST_OS=\"windows\"" "-DARDUINO_FQBN=\"esp32:esp32:dfrobot_beetle_esp32c6:UploadSpeed=921600,CDCOnBoot=cdc,CPUFreq=160,FlashFreq=80,FlashMode=qio,FlashSize=4M,PartitionScheme=default,DebugLevel=none,EraseFlash=none,JTAGAdapter=default\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 "@C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/flags/defines" "-IC:\\Users\\tao\\AppData\\Local\\Temp\\.arduinoIDE-unsaved2024327-1028-t9wqqk.94axi\\BasicExample" -iprefix "C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/include/" "@C:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/flags/includes" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\esp32-arduino-libs\\idf-release_v5.1-3662303f312/esp32c6/qio_qspi/include" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\cores\\esp32" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\variants\\dfrobot_beetle_esp32c6" "-Id:\\Arduino\\Sketchbook\\libraries\\FastLEDHub\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\FastLED\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\ArduinoJson\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\LinkedList" "-Id:\\Arduino\\Sketchbook\\libraries\\ESPEssentials\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\ArduinoOTA\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\Network\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\Update\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\FS\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\HTTPUpdateServer\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\SPIFFS\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\WebServer\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\WiFiManager" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\WiFi\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\DNSServer\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\AsyncUDP\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\Ticker\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\LittleFS\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\HTTPClient\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\NetworkClientSecure\\src" "-Id:\\Arduino\\Sketchbook\\libraries\\WebSockets\\src" "-IC:\\Users\\tao\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\3.0.0-rc1\\libraries\\ESPmDNS\\src" "@C:\\Users\\tao\\AppData\\Local\\Temp\\arduino\\sketches\\02B62C00B6984C7134C611F230200084/build_opt.h" "@C:\\Users\\tao\\AppData\\Local\\Temp\\arduino\\sketches\\02B62C00B6984C7134C611F230200084/file_opts" "d:\\Arduino\\Sketchbook\\libraries\\FastLED\\src\\power_mgt.cpp" -o "C:\\Users\\tao\\AppData\\Local\\Temp\\arduino\\sketches\\02B62C00B6984C7134C611F230200084\\libraries\\FastLED\\power_mgt.cpp.o"

Using library FastLEDHub at version 2.2.0 in folder: D:\Arduino\Sketchbook\libraries\FastLEDHub

**Comment by huster-songtao** [comment]
run the code below:

```
#include <FastLEDHub.h>

#include "Animations/Confetti.h"
#include "Animations/Color.h"
#include "Animations/Gradient.h"
#include "Animations/Rainbow.h"
#include "Animations/RGBWave.h"

#define NUM_LEDS 100
#define DATA_PIN 6
#define LED_TYPE WS2813
#define RGB_ORDER RGB

CRGB leds[NUM_LEDS];

void setup()
{
  String projectName = "Basic Example";
  bool enableGammaCorrection = true;
  FastLEDHub.initialize(projectName, enableGammaCorrection);
  // FastLED.addLeds<WS2812,DATA_PIN,RGB>(leds,NUM_LEDS);
  FastLEDHub.addLeds<LED_TYPE, DATA_PIN, RGB_ORDER>(leds, NUM_LEDS);

  FastLEDHub.registerAnimation(new Color("Color"));
  FastLEDHub.registerAnimation(new Gradient("Gradient"));
  FastLEDHub.registerAnimation(new Rainbow("Rainbow"));
  FastLEDHub.registerAnimation(new RGBWave("RGB Wave"));
  FastLEDHub.registerAnimation(new Confetti("Confetti"));

  FastLEDHub.registerSlider(new Slider("Saturation", 0, 255, 255, 1, "palette2"));

  FastLEDHub.registerColorPicker(new ColorPicker("Primary Color", CRGB(255, 0, 0)));
  FastLEDHub.registerColorPicker(new ColorPicker("Secondary Color", CRGB(0, 255, 0)));
}

void loop()
{
  FastLEDHub.handle();
}

```

**Comment by huster-songtao** [comment]
FQBN: esp32:esp32:XIAO_ESP32C3
Using board 'XIAO_ESP32C3' from platform in folder: C:\Users\tao\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-rc1
Using core 'esp32' from platform in folder: C:\Users\tao\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-rc1

I change ESP32C6 to ESP32C3

d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:266:29: error: 'RMTMEM' was not declared in this scope
  266 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:347:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  347 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out

**Comment by srwi** [comment]
It looks like a FastLED issue to me. Could you please try the FastLED blink example to see whether the problem persists?

https://github.com/FastLED/FastLED/blob/master/examples/Blink/Blink.ino

**Comment by huster-songtao** [comment]
FastLED do not support esp32 3.0 version

**Comment by srwi** [comment]
Yes, the issue should be opened in https://github.com/FastLED/FastLED instead.
